FROM hamadakoki/codalab:legacy-py37-ruby-01
# ベースにするイメージを指定

#RUN apt-get update -qq && apt-get install -y build-essential vim git make 
# RailsのインストールやMySQLへの接続に必要なパッケージをインストール


RUN git clone https://github.com/hamadakoki/pwscup2023.git

